begin;

set local lock_timeout = '3s';
set local statement_timeout = '15s';

-- Optional per-language SEO overrides. An empty object preserves every existing
-- title, meta description and H1 generated by the website today.
alter table public.products
  add column if not exists seo jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'products_seo_object'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_seo_object check (jsonb_typeof(seo) = 'object');
  end if;
end;
$$;

comment on column public.products.seo is
  'Per-language SEO overrides: {"en":{"title":"...","description":"...","h1":"..."}}. Supported languages: en, zh, es, fr, de, it. Missing or blank fields use generated defaults. Does not change product URLs.';

-- Reuse the existing products RLS policies: public reads only active products;
-- approved staff edit products. No new table, grants or privileged function.
notify pgrst, 'reload schema';

commit;
